name: Business Central Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t kibexd24/murimatestbcscript:latest .
        docker push kibexd24/murimatestbcscript:latest

    # Step 4: Deploy to Test Environment
    - name: Deploy to Test Environment
      run: |
        docker pull kibexd24/murimatestbcscript:latest
        docker run -d --name business-central-test -p 8080:80 kibexd24/murimatestbcscript:latest
