name: Business Central Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        version: latest

    - name: Install BC Container Helper
      run: |
        Install-Module -Name 'Microsoft.Dynamics.Nav.ContainerHelper' -Force
        Import-Module 'Microsoft.Dynamics.Nav.ContainerHelper'

    - name: Build Docker Image
      run: |
        docker build -t bc24bcscript:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag bc24bcscript:latest ${{ secrets.DOCKER_USERNAME }}/bc24bcscript:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/bc24bcscript:latest